config/routes.rb
Rails.application.routes.draw do
  root to: "image_search#search"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :image_search do
    get "search" => :search
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_search_result.rb
class ImageSearchResult
  attr_reader :url, :alt

  def initialize(url:, alt: "image search result")
    @url = url
    @alt = alt
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  encrypts :email, :name
  blind_index :email, :name

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user

  private

  def authenticate_user
    @current_user ||= session[:user_id].present? ? User.find_by(id: session[:user_id]) : nil
    unless @current_user.present?
      session[:return_to] ||= request.url
      redirect_to login_url, notice: "You do not have permission to access that page"
    end
  end
end

app/controllers/image_search_controller.rb
class ImageSearchController < ApplicationController
  class UnrecognizedProvider < StandardError; end
  MULTI_PROVIDER = "multi".freeze
  DEFAULT_PROVIDER = MULTI_PROVIDER.freeze
  PROVIDER_OPTIONS = {
    "Multi" => "multi",
    "Unsplash" => "unsplash",
    "Pixabay" => "pixabay",
    "Pexels" => "pexels",
    "Flickr" => "flickr",
    "Shutterstock" => "shutterstock"
  }.freeze

  def search
    @provider = params[:provider]&.strip&.downcase || DEFAULT_PROVIDER
    @query = params[:q]&.strip&.downcase
    NewRelic::Agent.add_custom_attributes(provider: @provider, query: @query, user_id: @current_user.id)
    @images = []
    return render :index if @query.blank?

    @images =
      case @provider
      when Clients::Unsplash::UNSPLASH_PROVIDER
        Clients::Unsplash.search(@query)
      when Clients::Pixabay::PIXABAY_PROVIDER
        Clients::Pixabay.search(@query)
      when Clients::Pexels::PEXELS_PROVIDER
        Clients::Pexels.search(@query)
      when Clients::Flickr::FLICKR_PROVIDER
        Clients::Flickr.search(@query)
      when Clients::Shutterstock::SHUTTERSTOCK_PROVIDER
        Clients::Shutterstock.search(@query)
      when MULTI_PROVIDER
        Thread.abort_on_exception = true
        [
          Thread.new { Clients::Unsplash.search(@query) },
          Thread.new { Clients::Pixabay.search(@query) },
          Thread.new { Clients::Pexels.search(@query) },
          Thread.new { Clients::Flickr.search(@query) },
          Thread.new { Clients::Shutterstock.search(@query) }
        ].flat_map(&:value)
      else
        raise UnrecognizedProvider, params[:provider].to_s
      end
    flash.now[:notice] = "#{provider_message} any images for '#{@query}'" if @images.blank?
    render :index
  rescue UnrecognizedProvider
    flash.now[:alert] = "Unrecognized provider '#{params[:provider]}'"
    render :index
  end

  private

  def provider_message
    if @provider == MULTI_PROVIDER
      "No availible providers had"
    else
      "#{@provider.titleize} didn't have"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  def new
    if session[:user_id]
      redirect_to session.delete(:return_to) || root_path
    else
      render :new
    end
  end

  def create
    user = User.find_by(email: params[:email])

    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      flash.discard
      audit_login_attempt(user_id: user&.id, user_email: params[:email], success: true)
      redirect_to session.delete(:return_to) || root_path
    else
      audit_login_attempt(user_id: user&.id, user_email: params[:email], success: false)
      redirect_to login_url, alert: "Invalid email/password combination"
    end
  end

  def destroy
    reset_session
    redirect_to login_url, notice: "Succesfully logged out"
  end

  private

  def audit_login_attempt(user_id:, user_email:, success:)
    NewRelic::Agent.record_custom_event(
      "AccountAccessAudit",
      "action" => "user.login",
      "attributes" => {
        "user_id" => user_id,
        "user_email" => user_email,
        "login_time" => Time.now.to_i,
        "success" => success
      }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_search_helper.rb
module ImageSearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/image_search/_image.html.erb
<%= image_tag(image.url, alt: image.alt, class: "image-result") %>

app/views/image_search/index.html.erb
<div class="index-container" data-controller="search">
  <div class="form-container">
    <%= form_with(url: search_path, method: "get", local: true, class: "search-form") do |f| %>
      <div class="field has-addons">
        <p class="control">
          <span class="select">
            <%= f.select(
              :provider,
              options_for_select(
                ImageSearchController::PROVIDER_OPTIONS,
                @provider
              )
            ) %>
          </span>
        </p>
        <div class="control image-search-input-container">
          <%= f.text_field(
            :q,
            value: @query,
            class: "input image-search-input",
            placeholder: "Search for an image by keyword...",
            autocomplete: "off",
            autofocus: "true",
            type: "search",
            data: { "search-target": "searchInput" }
          ) %>
        </div>
        <div class="control">
          <button class="button is-info" type="submit" data-disable-with="Search" data-action="click->search#loading">
            <span class="search-button-small">
              <%= fa_icon("search", class: "fas") %>
            </span>
            <span class="search-button-large">Search</span>
          </button>
        </div>
      </div>
    <% end %>
  </div>

  <div class="loader-wrapper" data-search-target="loaderWrapper">
    <div class="loader is-loading"></div>
  </div>

  <div class="image-results-container">
    <%= render(partial: 'image_search/image', collection: @images, as: :image) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%# https://github.com/turbolinks/turbolinks/issues/430 %>
    <%# <meta name="turbolinks-cache-control" content="no-cache"> %>
    <title>Flashcard Images</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation" data-controller="main-nav">
      <div class="navbar-brand">
        <%= link_to(root_path, class: "navbar-item") do %>
          <span class="navbar-title has-text-weight-semibold">Flashcard Images</span>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-main-nav-target="mainNavBurger" data-action="click->main-nav#toggle">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu main-nav-menu" data-main-nav-target="mainNavMenu">
        <div class="navbar-start main-nav-items">
          <%= link_to(search_path, class: "navbar-item has-text-weight-bold") do %>
            <span class="icon is-small">
              <i class="fas fa-search"></i>
            </span>
            <span>Image Search</span>
          <% end %>
        </div>

        <div class="navbar-end"></div>
        <% if @current_user.present? %>
          <%= link_to('Log out', logout_path, method: :delete, class: "navbar-item button is-small is-danger is-outlined logout-button") %>
        <% else %>
          <%= link_to('Log in', login_path, class: "navbar-item button is-small is-success login-button") %>
        <% end %>
      </div>
    </nav>

    <div class="page-container">
      <% if flash[:alert] %>
        <div class="flash notification is-danger" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:alert] %></p>
        </div>
      <% elsif flash[:notice] %>
        <div class="flash notification is-warning" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:notice] %></p>
        </div>
      <% elsif flash[:success] %>
        <div class="flash notification is-success" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:success] %></p>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>